---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  ansible_verbose: true
  # ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_chef_omnibus: false
  require_ansible_omnibus: true
  # require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh
  ansible_binary_path: /usr/local/bin
  require_pip3: true

platforms:
  - name: ubuntu-22.04
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: centos-8-Stream
  - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
  - name: default-python3
    run_list:
    attributes:
  - name: default-virtualenv
    run_list:
    attributes:
  - name: default-pyinstaller
    run_list:
    attributes:
