---

#- name: git clone floss
#  git:
#    repo=https://github.com/fireeye/flare-floss.git
#    dest={{ toolsetdir }}/floss
#    version={{ floss_version }}

- name: ensure development packages are present
  package: name={{ item }} state=present
  with_items: "{{ floss_dev_pkg }}"

- include: pip-upgrade.yml

- name: install floss source dependencies
  pip:
    name: "{{ item }}"
    state: present
    executable: "{{ floss_pip }}"
  with_items:
    - pytest
## https://github.com/erocarrera/pefile/issues/105
    - https://github.com/erocarrera/pefile/archive/master.zip

- block:
    - name: install floss with pip
      pip:
        name: "{{ floss_pip_module }}"
        state: present
        executable: "{{ floss_pip }}"
    - name: default floss executable
      template: src=floss.j2 dest=/usr/local/bin/floss.py mode=0755
  when: floss_virtualenv_path is not defined or not floss_virtualenv_path

- block:
    - name: virtualenv dependencies
      package: name={{ item }} state=present
      with_items: "{{ floss_virtualenv }}"

    - name: ensure virtualenv user {{ floss_virtualenv_user }} exists
      user:
        name: "{{ floss_virtualenv_user }}"
        home: "{{ floss_virtualenv_home }}"
        state: present

    - name: install floss python bindings - virtualenv
      pip:
        name: "{{ floss_pip_module }}"
        state: present
        virtualenv: "{{ floss_virtualenv_path }}"
        virtualenv_python: "{{ floss_python }}"
## FIXME! end with owner root
      become: yes
      become_user: "{{ floss_virtualenv_user }}"

## FIXME! not idempotent
#    - name: ensure right permissions
#      file: "dest={{ floss_virtualenv_path }} state=directory owner={{ floss_virtualenv_user }} recurse=yes"
  when: floss_virtualenv_path is defined and floss_virtualenv_path
