---

- name: Ensure tools dir exists
  ansible.builtin.file:
    path: "{{ toolsetdir }}"
    state: directory
    mode: '0755'

- name: Ensure development packages are present
  ansible.builtin.package:
    name: "{{ floss_dev_pkg }}"
    state: "present"
  register: pkg_result
  until: pkg_result is success

- name: Import pip-upgrade
  ansible.builtin.import_tasks: pip-upgrade.yml

- name: Copy floss requirements
  ansible.builtin.template:
    src: requirements.txt.j2
    dest: "{{ toolsetdir }}/requirements.txt"
    mode: '0600'

- name: System pip
  when: floss_virtualenv_path is not defined or floss_virtualenv_path | length <= 0
  block:
    - name: Ensure floss is present
      ansible.builtin.pip:
        requirements: "{{ toolsetdir }}/requirements.txt"
        executable: "{{ pip_bin | default('pip3') }}"
      register: pkg_result
      until: pkg_result is success
    - name: Default floss executable
      ansible.builtin.template:
        src: floss.j2
        dest: /usr/local/bin/floss.py
        mode: '0755'

- name: Virtualenv pip
  when: floss_virtualenv_path is defined and floss_virtualenv_path | length > 0
  block:
    - name: Virtualenv dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ floss_virtualenv_pkg | default(_floss_virtualenv_pkg) }}"
      register: pkg_result
      until: pkg_result is success

    - name: Ensure virtualenv user exists - {{ floss_virtualenv_user }}
      ansible.builtin.user:
        name: "{{ floss_virtualenv_user }}"
        home: "{{ floss_virtualenv_home }}"
        state: present

    - name: Install floss python bindings - virtualenv
      ansible.builtin.pip:
        requirements: "{{ toolsetdir }}/requirements.txt"
        state: present
        virtualenv: "{{ floss_virtualenv_path }}"
        virtualenv_python: "{{ floss_python | default(_floss_python) }}"
      ## FIXME! end with owner root
      become: yes
      become_user: "{{ floss_virtualenv_user }}"
      register: pkg_result
      until: pkg_result is success

      ## FIXME! not idempotent
      # - name: ensure right permissions
      #   ansible.builtin.file: "dest={{ floss_virtualenv_path }} state=directory owner={{ floss_virtualenv_user }} recurse=yes"
